export const constants = {
  TRANSPORT_OBJECT: 'TRANSPORT_OBJECT',
  SCREEN_RECORD_VIDEO: 'SCREEN_RECORD_VIDEO',
  WEBCAM_VIDEO: 'WEBCAM_VIDEO',
  HEIMDALL_ACTIVE: 'HEIMDALL_ACTIVE',
  HEIMDALL_INACTIVE: 'HEIMDALL_INACTIVE',
  ACTIVE_TIMESTAMP: 'ACTIVE_TIMESTAMP',
  STOP_HEIMDALL: 'STOP_HEIMDALL',
  SET_HEIMDALL_ON_QUIT_HANDLER: 'SET_HEIMDALL_ON_QUIT_HANDLER',
  HEIMDALL_ON_QUIT_HANDLER_DATA: 'HEIMDALL_ON_QUIT_HANDLER_DATA',
};
